language: ruby
rvm:
  - 2.1.2
  - 1.9.3
before_install:
  - gem update bundler
gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
notifications:
  email:
    recipients:
      - financedev@envato.com
