language: ruby
rvm:
  - 2.4.2
before_install:
  - gem update bundler
gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_5_0.gemfile
notifications:
  email:
    recipients:
      - financedev@envato.com
script: "bundle exec rake spec"
