---
name: tests
on: [ push, pull_request ]
jobs:
  test:
    name: 'Test { ruby: ${{ matrix.ruby }}, gems: ${{ matrix.gemfile }} }'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.7', '3.0' ]
        gemfile: [ rails-5.2, rails-6.0, rails-6.1 ]
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: RSpec
        run: bundle exec rspec
